### ISSUE TITLE
Add a parameter for what tags cause what type of update

### ISSUE THREAD

**Issue by MariusStorhaug** [PSModule/Auto-Release#13]
Example interface:

```yml
versionTags:
  major:
    - major
    - breaking
  minor:
    - minor
    - feature
    - improvement
    - enhancement
  patch:
    - patch
    - bug
    - fix
```
